# Generated by Django 5.0.6 on 2024-10-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
